item {
    id: 1
    name: 'Cloth mask'
}

item {
    id: 2
    name: 'No face mask'
}

item {
    id: 3
    name: 'Surgical mask'
}

item {
    id: 4
    name: 'N95 mask'
}

item {
    id: 5
    name: 'Mask worn incorrectly'
}